export const PRINTERS = [
  {
    id: 1,
    area: "Desserts",
    ip: "192.168.1.204",
    print: ["Desserts", "Coffee & Tea", "Cocktails"],
  },
  {
    id: 2,
    area: "Kitchen Upper",
    ip: "192.168.1.205",
    print: [
      "Starters",
      "Chicken Dishes",
      "Fish Dishes",
      "Burgers",
      "Steaks",
      "Mexican Dishes",
      "Vegan Dishes",
      "Sides",
      "Free Sides",
      "Sauce",
      "Kids Menu",
      "Extra Sides",
    ],
  },
  {
    id: 3,
    area: "Kitchen Fryer",
    ip: "192.168.1.202",
    print: [
      "Starters",
      "Chicken Dishes",
      "Fish Dishes",
      "Burgers",
      "Steaks",
      "Mexican Dishes",
      "Vegan Dishes",
      "Sides",
      "Free Sides",
      "Sauce",
      "Kids Menu",
      "Extra Sides",
    ],
  },
  {
    id: 4,
    area: "Kitchen Grill",
    ip: "192.168.1.203",
    print: [
      "Starters",
      "Chicken Dishes",
      "Fish Dishes",
      "Burgers",
      "Steaks",
      "Mexican Dishes",
      "Vegan Dishes",
      "Sides",
      "Free Sides",
      "Sauce",
      "Kids Menu",
      "Extra Sides",
    ],
  },
  {
    id: 5,
    area: "Bar",
    ip: "192.168.1.110",
    print: ["Wines", "Beers", "Spirits", "Soft Drinks"],
  },
  {
    id: 6,
    area: "Reception",
    ip: "192.168.1.206",
    print: ["Bill"],
  },
  {
    id: 7,
    area: "Pass",
    ip: "192.168.1.201",
    print: [
      "Starters",
      "Chicken Dishes",
      "Fish Dishes",
      "Burgers",
      "Steaks",
      "Mexican Dishes",
      "Vegan Dishes",
      "Sides",
      "Free Sides",
      "Sauce",
      "Kids Menu",
      "Extra Sides",
    ],
  },
  {
    id: 8,
    area: "Kitchen Pass",
    ip: "192.168.1.211",
    print: [
      "Starters",
      "Chicken Dishes",
      "Fish Dishes",
      "Burgers",
      "Steaks",
      "Mexican Dishes",
      "Vegan Dishes",
      "Sides",
      "Free Sides",
      "Sauce",
      "Kids Menu",
      "Extra Sides",
    ],
  },
];

